### ISSUE TITLE
Template bug with docker_daemon integration and tags

### ISSUE THREAD

**Issue by comptonqc** [DataDog/puppet-datadog-agent#268]
If you specify any tags for the docker_daemon integration:

```
node default {
  include datadog_agent
  class { 'datadog_agent::integrations::docker_daemon':
    tags => [ "configured-by:puppet" ],
  }
}
```

Then the generated config file `/etc/dd-agent/conf.d/docker_daemon.yaml` does not parse:
```
[centos@ip-10-67-7-158 puppet]$ sudo service datadog-agent info
2016-12-08 21:00:00,010 | ERROR | dd.collector | utils.dockerutil(dockerutil.py:108) | Docker check configuration file is invalid. The docker check and other Docker related components will not work.
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/utils/dockerutil.py", line 104, in get_check_config
    check_config = check_yaml(conf_path)
  File "/opt/datadog-agent/agent/util.py", line 110, in check_yaml
    check_config = yaml.load(f.read(), Loader=yLoader)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "_yaml.pyx", line 707, in _yaml.CParser.get_single_node (ext/_yaml.c:8308)
  File "_yaml.pyx", line 725, in _yaml.CParser._compose_document (ext/_yaml.c:8581)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:9306)
  File "_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10838)
  File "_yaml.pyx", line 774, in _yaml.CParser._compose_node (ext/_yaml.c:9284)
  File "_yaml.pyx", line 851, in _yaml.CParser._compose_sequence_node (ext/_yaml.c:10311)
  File "_yaml.pyx", line 776, in _yaml.CParser._compose_node (ext/_yaml.c:9306)
  File "_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node (ext/_yaml.c:10868)
  File "_yaml.pyx", line 905, in _yaml.CParser._parse_next_event (ext/_yaml.c:11045)
ParserError: while parsing a block mapping
  in "<byte string>", line 30, column 5
did not find expected key
  in "<byte string>", line 82, column 7
2016-12-08 21:00:00,011 | ERROR | dd.collector | utils.dockerutil(dockerutil.py:116) | No instance was found in the docker check configuration. Docker related collection will not work.
```

Line 82:
```
[centos@ip-10-67-7-158 puppet]$ nl -ba /etc/dd-agent/conf.d/docker_daemon.yaml | grep -C5 82
    77	
    78	
    79	
    80	    ## Tagging
    81	    ##
    82	      tags:
    83	          - configured-by:puppet
    84	
    85	    # You can add extra tags to your Docker metrics with the tags list option.
    86	    # Example: ["extra_tag", "env:testing"]
    87	    #
```

The fix is to edit `templates/agent-conf.d/docker_daemon.yaml.erb` and remove the extraneous spaces:
```
[centos@ip-10-67-7-158 puppet]$ diff -u modules/datadog_agent/templates/agent-conf.d/docker_daemon.yaml.erb{.bak,}
--- modules/datadog_agent/templates/agent-conf.d/docker_daemon.yaml.erb.bak	2016-12-08 21:06:00.262689128 +0000
+++ modules/datadog_agent/templates/agent-conf.d/docker_daemon.yaml.erb	2016-12-08 21:06:04.185629458 +0000
@@ -80,7 +80,7 @@
     ## Tagging
     ##
 <% if @tags and ! @tags.empty? -%>
-      tags:
+    tags:
   <%- Array(@tags).each do |tag| -%>
     <%- if tag != '' -%>
           - <%= tag %>
```

I don't have the time to open a PR right now, but it's a simple fix.

**Comment by truthbk** [comment]
@comptonqc thank you very much for this. I'm surprised this wasn't caught by the spec tests (I guess we'll have to take a look at those too). I'll implement this as soon as I get a minute 🙇

**Comment by comptonqc** [comment]
We're ramping up our use of Datadog, so expect a lot of issues from me over the next little while as I find things. ;-)
