### ISSUE TITLE
excluded_interface_re has wrong datatype

### ISSUE THREAD

**Issue by florusboth** [DataDog/puppet-datadog-agent#695]
Trying to add excluded_interface_re: to my network/conf.yaml on a Kubernetes node to exclude a lot of those vNICs it spawns, I found that the puppet-datadog-agent specifies the datatype as an array of string for excluded_interface_re.

Using this is hieradata:

```
datadog_agent::integrations::network::excluded_interface_re: 
  - vethwep.*
````

will populate thet network/conf.yaml file on the server but datadog status gives an error:
```
    network (2.1.2)
    ---------------
      Instance ID: network:9358677f0d90eae3 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/network.d/conf.yaml
      Total Runs: 11
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      Last Execution Date : 2021-05-07 11:02:30 UTC (1620385350000)
      Last Successful Execution Date : Never
      Error: unhashable type: 'list'
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 897, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/network/network.py", line 105, in check
          self._exclude_iface_re = re.compile(exclude_re)
        File "/opt/datadog-agent/embedded/lib/python3.8/re.py", line 252, in compile
          return _compile(pattern, flags)
        File "/opt/datadog-agent/embedded/lib/python3.8/re.py", line 294, in _compile
          return _cache[type(pattern), pattern, flags]
      TypeError: unhashable type: 'list'
```

Checking the documentation for the network/conf.yaml file (https://github.com/DataDog/integrations-core/blob/master/network/datadog_checks/network/data/conf.yaml.default) shows this:
```
# excluded_interface_re: <NETWORK_INTERFACE_NAME>.*
```

Updating the network/conf.yaml file to this format does work after a datadog-agent restart

I will create a PR to fix the datatype.

/florus

**Comment by florusboth** [comment]
PR https://github.com/DataDog/puppet-datadog-agent/pull/696 submitted

**Comment by florusboth** [comment]
fix implemented
